#pragma once
const int diCaudT = 18, diCaudH = 19, diMarchaOn = 33;
const int diPresHi = 35, diPresLow = 37;
const int doCalentador = 23, doCompressor = 25, doBombas = 27;
const int doValvula4Vias = 29, doValvulaAcs = 31;
const int doTriac01 = 11, doBuzzer = 12;

volatile int estadoMaquina;
int caudT, c1T, c2T, c3T, caudTacu;
int caudH, c1H, c2H, c3H, caudHacu;
int contTempDes, contTempCompressor, contPressHi;
int contPressLow, contTempDescarga;
float tempCompressor, t5Comp, t4Comp, t3Comp, t2Comp, t1Comp, tempCompressorAcu;
float tempAcs, t1Acs, t2Acs, t3Acs, tempAcsAcu;
float tempOutH, tempInH, tempOutT, tempInT, tempDescarga, tempAdmision;
float t1Oh, t2Oh, t3Oh, tempOutHacu;
float t1Ih, t2Ih, t3Ih, tempInHacu;
float t1Des, t2Des, t3Des, tempDescargaAcu;
bool flagTempCompressor, flagTempDescarga;
unsigned long valvulaAcsStart, pumpStart, ingresoE7, ingresoE71;
const uint8_t GAP_ACS = 5;
unsigned long periodoRefresco, compressorStart, saltoE1;
unsigned long dontStuckPumpsStartActivation, dontStuckPumpsStart, ingresoE3;
unsigned long ingresoDescanso;
volatile MenuId menuActual;
volatile uint8_t nroAlarma, acsSetpoint, acsSetpointEdit;
uint8_t alarmaEeprom;
bool deltaAcsElectricResult, flagCaudT, flagCaudH;
bool flagPresHi, flagPresLow, flagTempAdm;
volatile bool modoFrio, alarmaActiva, heatingOff, flagBuzzer;
bool flagMarchaOn, senalStart, senalStop;
volatile bool enableFlowAlarm, enableAcs, enableAcsDeltaElectrico;
volatile bool enableElectricAcs;
int valorDoBombas, valorDoCalentador, valorDoCompressor;
int valorDoVacs, valorDoV4v;
volatile int valorDoBuzzer;
